import type { CharacterId } from './types'

export const PERSONALITY_FACTS: Record<CharacterId, readonly string[]> = {
  vesper: [
    'Vesper alphabetizes her tea collection by mood.',
    'She can peel an apple in one unbroken spiral.',
    'Her favorite dessert is honeyed pear tart.',
    'She names every revolver, but never admits it.',
    'Rain against a window helps her think.',
    'She keeps score during friendly card games.',
    'Vesper wakes early for perfectly quiet streets.',
    'She presses tiny flowers inside old field manuals.',
    'Her handwriting is impossibly small and neat.',
    'She loves puzzles with only one correct answer.',
    'Vesper orders coffee black and steals one pastry.',
    'She is secretly wonderful at ballroom dancing.',
    'Her favorite color is candlelight gold.',
    'She counts stairs without realizing it.',
    'She keeps a lucky brass button in her pocket.',
    'Vesper prefers cats that pretend not to care.',
    'She can identify constellations through thin clouds.',
    'Her ideal evening includes a mystery novel.',
    'She always chooses the window seat.',
    'Vesper sharpens pencils with suspicious precision.',
    'She likes lemon cakes with too much zest.',
    'Her laugh is much louder than expected.',
    'She collects beautiful matchboxes from old inns.',
    'Vesper plans picnics down to the napkin folds.',
    'She hums quietly while cleaning her gear.',
    'Her favorite season is the first cold week.',
    'She can nap anywhere except a comfortable bed.',
    'Vesper loves watching elaborate domino setups fall.',
    'She always notices when someone changes their hair.',
    'Her comfort meal is rosemary potatoes and eggs.',
    'She keeps every kind note she receives.',
    'Vesper is fiercely competitive at darts.',
    'She prefers silver jewelry with simple shapes.',
    'She practices compliments before saying them aloud.',
    'Her perfect vacation is a quiet mountain cabin.',
    'Vesper knows six ways to tie a scarf.',
    'She likes songs with clever, complicated lyrics.',
    'Her shelves are tidy; her desk drawer is chaos.',
    'She makes excellent jam and terrible bread.',
    'Vesper always saves the crispiest bite for last.',
    'She likes museums most when they are nearly empty.',
    'Her favorite animal is the red fox.',
    'She writes tomorrow’s list before sleeping.',
    'Vesper can whistle almost any melody once heard.',
    'She blushes whenever someone praises her cooking.',
    'Her favorite flowers are pale yellow irises.',
    'She leaves exact change plus a generous tip.',
    'Vesper loves the smell of new books.',
    'She owns one ridiculous hat and adores it.',
    'Her rare days off begin with cinnamon toast.',
  ],
  cinder: [
    'Scarlet hand-paints signs for every climate march.',
    'She never misses the local human-rights fundraiser.',
    'Her canvas tote is covered in protest pins.',
    'She volunteers at a neighborhood mutual-aid pantry.',
    'Scarlet brings extra sunscreen to outdoor rallies.',
    'She can turn any jacket into an upcycled favorite.',
    'Her climate-justice ideal has trains, trees, and safe sidewalks.',
    'She reads climate policy over spicy breakfast tacos.',
    'Scarlet always knows where the next march begins.',
    'She writes representatives with startling frequency.',
    'Her favorite posters demand dignity for everyone.',
    'She organizes coat drives before the first frost.',
    'Scarlet believes good trouble needs good snacks.',
    'She keeps reusable cups in every possible bag.',
    'Her balcony is a tiny pollinator garden.',
    'She loves union-made coffee and very loud music.',
    'Scarlet teaches friends how to register to vote.',
    'She can explain carbon pricing at a dinner party.',
    'Her favorite color is protest-poster red.',
    'She donates birthday money to refugee support groups.',
    'Scarlet carries chalk for spontaneous sidewalk messages.',
    'She helps newcomers feel welcome at every meeting.',
    'Her dream date ends at a community art show.',
    'She cries at successful human-rights lawsuits.',
    'Scarlet grows herbs in repurposed soup cans.',
    'She has strong opinions about protected bike lanes.',
    'Her favorite dessert is fair-trade chocolate cake.',
    'She shares petitions, then actually does the follow-up.',
    'Scarlet owns twelve bandanas and lends all of them.',
    'She spends Saturdays cleaning trails with friends.',
    'Her playlists alternate protest songs and bubblegum pop.',
    'She brings hand warmers to winter demonstrations.',
    'Scarlet can screen-print protest shirts after midnight.',
    'She celebrates every small local election victory.',
    'Her fridge is crowded with community-event flyers.',
    'She makes excellent vegetarian chili for volunteers.',
    'Scarlet insists every meeting include accessible seating.',
    'She keeps a little library beside her front door.',
    'Her favorite holiday tradition is a charity fun run.',
    'She sends thank-you notes to public-school teachers.',
    'Scarlet loves documentaries about ordinary organizers.',
    'She knows which brands repair instead of replace.',
    'Her dream is to restore a neglected city park.',
    'She carries spare menstrual products for anyone asking.',
    'Scarlet never lets a cruel joke pass unchallenged.',
    'She makes friendship bracelets in movement colors.',
    'Her proudest skill is turning outrage into a plan.',
    'She believes hope works best with a clipboard.',
    'Scarlet relaxes by watching tiny baking videos.',
    'After every rally, she buys everyone ice cream.',
  ],
  bastion: [
    'Bastion bakes bread sturdy enough for any journey.',
    'She keeps a tiny sewing kit inside her armor.',
    'Her favorite meal is mushroom stew with dumplings.',
    'She loves lifting heavy things for grateful neighbors.',
    'Bastion remembers every promise she makes.',
    'She braids her hair when solving hard problems.',
    'Her room contains more blankets than furniture.',
    'She carves little wooden animals during long watches.',
    'Bastion always volunteers to carry the picnic basket.',
    'She is gentle with spiders and relocates them outside.',
    'Her favorite flower is the sturdy little snowdrop.',
    'She laughs hardest at very bad puns.',
    'Bastion can repair almost any broken chair.',
    'She drinks warm milk with nutmeg before bed.',
    'Her hugs are famous throughout the company.',
    'She enjoys competitive arm wrestling a little too much.',
    'Bastion keeps emergency cookies in a shield compartment.',
    'She likes dogs that believe they are lap-sized.',
    'Her handwriting is broad, round, and cheerful.',
    'She sings old marching songs while doing laundry.',
    'Bastion collects smooth stones from meaningful places.',
    'She plans surprise parties with military precision.',
    'Her favorite weather is a soft, steady snowfall.',
    'She never starts dinner until everyone is seated.',
    'Bastion makes excellent hot cider.',
    'She loves historical dramas with elaborate costumes.',
    'Her guilty pleasure is glittery stationery.',
    'She checks every lock twice, then trusts it.',
    'Bastion teaches children how to build blanket forts.',
    'She keeps her oldest scarf despite countless repairs.',
    'Her ideal morning begins with stretching and toast.',
    'She apologizes to tables after bumping into them.',
    'Bastion knows the birthday of every squadmate.',
    'She gives practical gifts wrapped beautifully.',
    'Her favorite fruit is a perfectly crisp apple.',
    'She loves watching blacksmiths work.',
    'Bastion is terrible at whispering secrets.',
    'She keeps pressed leaves in her training journal.',
    'Her tea preference is strong, sweet, and enormous.',
    'She always offers the last chair to someone else.',
    'Bastion’s dream home has a huge communal table.',
    'She can knit one very specific kind of sock.',
    'Her favorite music has drums she can march to.',
    'She cries at reunions in adventure stories.',
    'Bastion makes friends with every innkeeper.',
    'She prefers sunrise hikes with plenty of snacks.',
    'Her armor polish smells faintly of oranges.',
    'She keeps a list of people who need checking on.',
    'Bastion treasures handmade gifts above everything.',
    'Her perfect evening is feeding a crowded table.',
  ],
  warden: [
    'Warden knows exactly how everyone takes their tea.',
    'She keeps fresh flowers beside every sickbed.',
    'Her favorite food is soft rice with ginger.',
    'She mends torn sleeves before anyone notices.',
    'Warden collects lullabies from every town she visits.',
    'She can make a room feel quieter by entering it.',
    'Her windowsill is crowded with medicinal herbs.',
    'She loves gentle watercolor landscapes.',
    'Warden never forgets to bring an umbrella.',
    'She writes letters for people who cannot find words.',
    'Her favorite animal is the luna moth.',
    'She keeps peppermint candies for nervous friends.',
    'Warden enjoys slow walks through botanical gardens.',
    'She has a surprisingly mischievous poker face.',
    'Her comfort book has been repaired seven times.',
    'She prefers lavender soap and clean linen.',
    'Warden makes tiny soups when someone feels ill.',
    'She hums while organizing medicine bottles.',
    'Her favorite season is tender early spring.',
    'She loves hearing people talk about their hometowns.',
    'Warden owns one pair of outrageously bright socks.',
    'She leaves encouraging notes inside borrowed books.',
    'Her ideal breakfast is peaches and warm oats.',
    'She can recognize friends by their footsteps.',
    'Warden is unbeatable at memory games.',
    'She saves ribbon from every meaningful gift.',
    'Her garden has a bench reserved for visitors.',
    'She prefers candlelight to harsh lamps.',
    'Warden knows when silence is the kinder answer.',
    'She bakes delicate almond biscuits on rainy days.',
    'Her laugh starts quietly and becomes contagious.',
    'She loves tiny birds with enormous confidence.',
    'Warden carries a comb for windswept companions.',
    'She makes birthdays feel like holidays.',
    'Her favorite color is lilac at dusk.',
    'She keeps a gratitude list in coded shorthand.',
    'Warden naps best beside a crackling fireplace.',
    'She can fold fitted sheets perfectly.',
    'Her dream trip follows old lighthouse roads.',
    'She enjoys guessing the ingredients in unfamiliar tea.',
    'Warden gives every plant a dignified name.',
    'She remembers stories better than dates.',
    'Her favorite dessert is vanilla custard with berries.',
    'She loves quietly watching markets open at dawn.',
    'Warden always carries an extra pair of gloves.',
    'She is deeply competitive about crossword puzzles.',
    'Her room smells like cedar and chamomile.',
    'She treasures candid photographs of her friends.',
    'Warden believes a warm meal solves many problems.',
    'Her perfect night ends with everyone safely home.',
  ],
  nyx: [
    'Nyx befriends alley cats by pretending not to.',
    'She orders noodles at the maximum spice level.',
    'Her favorite hour is exactly two in the morning.',
    'She collects earrings that do not quite match.',
    'Nyx reads ghost stories under three blankets.',
    'She knows every rooftop shortcut in the city.',
    'Her laugh appears when she is trying to look serious.',
    'She loves blackberries straight from the vine.',
    'Nyx can sleep through thunder but not dripping taps.',
    'She keeps movie-ticket stubs in her wallet.',
    'Her favorite color is blue just before sunrise.',
    'She is excellent at claw-machine games.',
    'Nyx wears perfume that smells faintly of rain.',
    'She loves tiny cafés with questionable lighting.',
    'Her comfort food is crispy scallion pancakes.',
    'She sketches strangers’ shoes while waiting.',
    'Nyx sends friends songs instead of long messages.',
    'She collects strange keys with unknown locks.',
    'Her ideal pet is an elderly one-eyed cat.',
    'She prefers silver nail polish chipped at the edges.',
    'Nyx knows several card tricks and one real trick.',
    'She steals blankets and denies everything.',
    'Her favorite flowers bloom only at night.',
    'She enjoys train rides to nowhere in particular.',
    'Nyx writes poetry and hides it extremely well.',
    'She can pick the ripest peach by scent.',
    'Her room is messy in a highly navigable way.',
    'She loves old buildings with secret staircases.',
    'Nyx always chooses the most dramatic umbrella.',
    'She makes exceptional midnight grilled cheese.',
    'Her playlists have titles nobody else understands.',
    'She prefers moonlit swims to sunny beaches.',
    'Nyx secretly enjoys cheerful romantic comedies.',
    'She keeps a coin from her first solo journey.',
    'Her favorite game is hide-and-seek, naturally.',
    'She loves the sound of a distant train.',
    'Nyx remembers every cat’s preferred scratching spot.',
    'She uses fancy bookmarks in cheap paperbacks.',
    'Her dream apartment has an impossible number of windows.',
    'She is always first to spot a shooting star.',
    'Nyx gives excellent gifts with no explanation.',
    'She likes smoky tea and sweet buns.',
    'Her handwriting changes with her mood.',
    'She has never returned a borrowed hoodie.',
    'Nyx relaxes by solving elaborate escape rooms.',
    'She keeps polished stones lined along the sill.',
    'Her favorite dessert is dark cherry ice cream.',
    'She enjoys museums after closing hours, somehow.',
    'Nyx always notices the nearest exit and bakery.',
    'Her best mornings begin very late.',
  ],
  tempest: [
    'Tempest opens windows whenever a storm arrives.',
    'She drums rhythms on every available tabletop.',
    'Her favorite snack is salted watermelon.',
    'She builds tiny radios from discarded parts.',
    'Tempest loves swimming when the water is cold.',
    'She can predict rain by the smell of stone.',
    'Her hair refuses to obey any brush.',
    'She collects glass marbles that resemble planets.',
    'Tempest dances while waiting for kettles to boil.',
    'She prefers fizzy drinks with too much lime.',
    'Her favorite color is electric blue.',
    'She once repaired a fan just to improve it.',
    'Tempest talks faster when she is excited.',
    'She loves concerts where the floor vibrates.',
    'Her ideal breakfast includes three kinds of fruit.',
    'She races elevators up the stairs.',
    'Tempest keeps spare batteries in labeled tins.',
    'She can whistle louder than anyone expects.',
    'Her favorite animal is the hummingbird.',
    'She enjoys photographing unusual cloud shapes.',
    'Tempest makes friendship bracelets with metallic thread.',
    'She loves roller skates and open plazas.',
    'Her room contains several harmless unfinished inventions.',
    'She orders dessert before choosing dinner.',
    'Tempest knows every good swimming hole nearby.',
    'She sleeps with a fan running all year.',
    'Her favorite candy crackles on the tongue.',
    'She keeps concert wristbands around her bedpost.',
    'Tempest is very bad at sitting through lectures.',
    'She makes excellent playlists for road trips.',
    'Her dream home has a rooftop weather station.',
    'She loves bright sneakers and reflective laces.',
    'Tempest names storms after inconvenient acquaintances.',
    'She can juggle three oranges for almost a minute.',
    'Her favorite dessert is lemon sorbet.',
    'She gives enthusiastic, slightly dangerous high-fives.',
    'Tempest fixes lamps before anyone asks.',
    'She likes science museums with working buttons.',
    'Her handwriting leans forward like it is running.',
    'She treasures voice messages full of laughter.',
    'Tempest prefers windy cliffs to quiet valleys.',
    'She grows mint because it survives her schedule.',
    'Her favorite films contain impossible airships.',
    'She turns chores into timed competitions.',
    'Tempest always carries a tiny screwdriver.',
    'She likes thunderstorms best when friends are nearby.',
    'Her perfect evening includes music and street food.',
    'She can make sparks dance between her fingertips.',
    'Tempest celebrates good news with cartwheels.',
    'She never refuses an invitation to karaoke.',
  ],
  briar: [
    'Briar grows roses in chipped teacups.',
    'She makes strawberry jam every early summer.',
    'Her favorite dress has enormous pockets.',
    'She talks to seedlings while watering them.',
    'Briar loves outdoor dances under string lights.',
    'She braids wildflowers into everyone’s hair.',
    'Her comfort meal is tomato soup and toast.',
    'She keeps bees and knows each hive’s temperament.',
    'Briar collects floral china with tiny cracks.',
    'She laughs whenever mud ruins her shoes.',
    'Her favorite color is the inside of a rose.',
    'She can identify herbs with her eyes closed.',
    'Briar makes excellent berry pies.',
    'She prefers handwritten invitations to formal events.',
    'Her room always contains one mysterious vine.',
    'She loves farmers’ markets before they get crowded.',
    'Briar presses leaves into homemade paper.',
    'She dances barefoot whenever possible.',
    'Her favorite animal is the sleepy bumblebee.',
    'She keeps ribbon tied around garden tools.',
    'Briar sends cuttings instead of greeting cards.',
    'She knows which flowers open after rain.',
    'Her ideal picnic includes cheese and plums.',
    'She enjoys painting little signs for herb pots.',
    'Briar is fiercely competitive at croquet.',
    'She wears perfume made from her own garden.',
    'Her favorite season is late, overgrown summer.',
    'She gives every scarecrow a proper backstory.',
    'Briar can weave a flower crown in minutes.',
    'She loves old songs with easy harmonies.',
    'Her dream cottage has a glass greenhouse.',
    'She keeps a secret stash of sour candies.',
    'Briar makes bouquets for people having hard weeks.',
    'She prefers freckles to perfect makeup.',
    'Her handwriting curls like climbing ivy.',
    'She knows how to remove almost any stain.',
    'Briar loves warm rain and garden mud.',
    'She collects recipes written in family margins.',
    'Her favorite dessert is rosewater shortbread.',
    'She can whistle birds into curious silence.',
    'Briar hosts dinners with mismatched plates.',
    'She dries orange slices for winter garlands.',
    'Her favorite jewelry is made from pressed petals.',
    'She believes every windowsill deserves something green.',
    'Briar relaxes by pruning plants at sunset.',
    'She never wastes the last spoonful of honey.',
    'Her perfect morning begins barefoot in the garden.',
    'She gives plants to friends moving somewhere new.',
    'Briar always smells faintly of crushed mint.',
    'She saves the first blossom of every spring.',
  ],
  seraph: [
    'Seraph watches sunrise even after very late nights.',
    'She knows the best pastry in every town.',
    'Her favorite fruit is a chilled golden peach.',
    'She collects feathers without taking them from birds.',
    'Seraph paints tiny suns on ordinary objects.',
    'She loves rooftop breakfasts with strong coffee.',
    'Her laugh makes other people start laughing.',
    'She keeps bright ribbons tied to her luggage.',
    'Seraph volunteers to take every group photograph.',
    'She can make pancakes shaped like animals.',
    'Her favorite color is apricot at dawn.',
    'She sings harmony without needing to practice.',
    'Seraph owns too many pairs of sunglasses.',
    'She sends postcards from places she barely visited.',
    'Her ideal meal is warm bread and citrus salad.',
    'She loves public gardens full of fountains.',
    'Seraph remembers compliments for years.',
    'She keeps a sketchbook of interesting doorways.',
    'Her favorite animal is the sun conure.',
    'She wears gold nail polish on difficult days.',
    'Seraph believes every room needs better lighting.',
    'She makes excellent orange marmalade.',
    'Her dream trip follows the coast by train.',
    'She enjoys teaching children simple songs.',
    'Seraph always finds the warmest patch of sunlight.',
    'She carries spare hair ties for everyone.',
    'Her favorite dessert is cardamom cream cake.',
    'She loves old theaters with painted ceilings.',
    'Seraph celebrates tiny victories with sparkling drinks.',
    'She can nap peacefully on sunny stone steps.',
    'Her handwriting is large, elegant, and optimistic.',
    'She gives plants more sunlight than instructions recommend.',
    'Seraph likes dresses that move when she spins.',
    'She keeps breakfast invitations delightfully informal.',
    'Her favorite season is the bright edge of spring.',
    'She enjoys portraits that catch people laughing.',
    'Seraph can braid ribbon into almost anything.',
    'She orders the most colorful thing on the menu.',
    'Her room smells like orange blossom and paper.',
    'She loves flying kites from windy hills.',
    'Seraph keeps every child’s drawing she receives.',
    'She is surprisingly skilled at table tennis.',
    'Her perfect afternoon includes a sunny bookshop.',
    'She makes playlists for the first day of trips.',
    'Seraph always opens curtains before making tea.',
    'She likes earrings that catch the light.',
    'Her comfort food is buttered noodles with herbs.',
    'She knows exactly when peaches become ripe.',
    'Seraph ends letters with a tiny drawn sun.',
    'Her best ideas arrive during long morning walks.',
  ],
}

export const personalityFact = (character: CharacterId, seed: number): string => {
  const facts = PERSONALITY_FACTS[character]
  return facts[Math.abs(seed) % facts.length]
}
