import type { CharacterId } from './types'

const RAW_PERSONALITY_FACTS: Record<CharacterId, readonly string[]> = {
  vesper: [
    'Vesper alphabetizes her tea collection by mood.',
    'She can peel an apple in one unbroken spiral.',
    'Her favorite dessert is honeyed pear tart.',
    'She names every revolver, but never admits it.',
    'Rain against a window helps her think.',
    'She keeps score during friendly card games.',
    'Vesper wakes early for perfectly quiet streets.',
    'She presses tiny flowers inside old field manuals.',
    'Her handwriting is impossibly small and neat.',
    'She loves puzzles with only one correct answer.',
    'Vesper orders coffee black and steals one pastry.',
    'She is secretly wonderful at ballroom dancing.',
    'Her favorite color is candlelight gold.',
    'She counts stairs without realizing it.',
    'She keeps a lucky brass button in her pocket.',
    'Vesper prefers cats that pretend not to care.',
    'She can identify constellations through thin clouds.',
    'Her ideal evening includes a mystery novel.',
    'She always chooses the window seat.',
    'Vesper sharpens pencils with suspicious precision.',
    'She likes lemon cakes with too much zest.',
    'Her laugh is much louder than expected.',
    'She collects beautiful matchboxes from old inns.',
    'Vesper plans picnics down to the napkin folds.',
    'She hums quietly while cleaning her gear.',
    'Her favorite season is the first cold week.',
    'She can nap anywhere except a comfortable bed.',
    'Vesper loves watching elaborate domino setups fall.',
    'She always notices when someone changes their hair.',
    'Her comfort meal is rosemary potatoes and eggs.',
    'She keeps every kind note she receives.',
    'Vesper is fiercely competitive at darts.',
    'She prefers silver jewelry with simple shapes.',
    'She practices compliments before saying them aloud.',
    'Her perfect vacation is a quiet mountain cabin.',
    'Vesper knows six ways to tie a scarf.',
    'She likes songs with clever, complicated lyrics.',
    'Her shelves are tidy; her desk drawer is chaos.',
    'She makes excellent jam and terrible bread.',
    'Vesper always saves the crispiest bite for last.',
    'She likes museums most when they are nearly empty.',
    'Her favorite animal is the red fox.',
    'She writes tomorrow’s list before sleeping.',
    'Vesper can whistle almost any melody once heard.',
    'She blushes whenever someone praises her cooking.',
    'Her favorite flowers are pale yellow irises.',
    'She leaves exact change plus a generous tip.',
    'Vesper loves the smell of new books.',
    'She owns one ridiculous hat and adores it.',
    'Her rare days off begin with cinnamon toast.',
  ],
  cinder: [
    'I live alone in a tiny apartment where the city never quite goes quiet.',
    'I am single, and my friends are much more invested in that fact than I am.',
    'I call my dad every Sunday even when we are still annoyed with each other.',
    'I once stopped speaking to my dad for a week over an argument about my career.',
    'I make up with my dad by sending him photos of meals I know he would like.',
    'I keep three emergency outfits hanging on the back of my bedroom door.',
    'I know which late-night diner has the best spicy breakfast tacos.',
    'I can turn almost any old jacket into something I would wear again.',
    'I grow basil, mint, and one stubborn tomato plant on my fire escape.',
    'I love very loud music when I am cleaning my apartment.',
    'I have a canvas tote covered in pins from places and causes I care about.',
    'I volunteer at the neighborhood pantry when my schedule allows it.',
    'I prefer trains, trees, and streets where people can actually walk safely.',
    'I write my representatives when an issue keeps me awake.',
    'I bring extra sunscreen whenever friends plan something outdoors.',
    'I organize a coat drive before the first cold weekend every year.',
    'I believe a good cause still needs good snacks.',
    'I keep reusable cups in more bags than I can remember owning.',
    'I teach friends how to register to vote without turning dinner into a lecture.',
    'I donate a little of every birthday check to a local refugee-support group.',
    'I have strong opinions about bike lanes but save them for people who ask.',
    'I never let a cruel joke sit comfortably in the room.',
    'I would love to help restore the neglected park near my building.',
    'I relax by watching tiny baking videos in bed.',
    'I make excellent vegetarian chili and terrible rice.',
    'I own twelve bandanas and somehow lend out all twelve.',
    'I spend some Saturdays cleaning trails with friends.',
    'I alternate old protest songs with shameless bubblegum pop.',
    'I have a favorite bookstore cashier who always saves recommendations for me.',
    'I order the same drink at my corner café and pretend it is adventurous.',
    'I keep a little library shelf beside my apartment door.',
    'I love documentaries, romantic comedies, and aggressively bad reality television.',
    'I buy flowers for myself whenever the week has been difficult.',
    'I wear red lipstick when I need to feel braver than I am.',
    'I have cried on the subway and survived the embarrassment.',
    'I text my friends when I get home because they refuse to stop asking.',
    'I make friendship bracelets during long phone calls.',
    'I know exactly which rooftop has the best view of the city lights.',
    'I keep spare shoes under my desk for walking home.',
    'I am trying to learn how to cook my dad’s soup without calling him for help.',
    'I keep community-event flyers on my fridge beside takeout menus.',
    'I love the strange quiet that arrives just before the morning trains begin.',
    'I always have a book in my bag and rarely finish it on time.',
    'I celebrate small victories with ice cream from the shop downstairs.',
    'I can screen-print a decent shirt after midnight.',
    'I send thank-you notes when someone makes my neighborhood feel kinder.',
    'I want a relationship someday, but I am not interested in forcing one.',
    'I have deleted and reinstalled the same dating app more than once.',
    'I turn frustration into lists because lists make everything feel possible.',
    'I think hope works best when somebody remembers to bring a clipboard.',
  ],
  bastion: [
    'Bastion bakes bread sturdy enough for any journey.',
    'She keeps a tiny sewing kit inside her armor.',
    'Her favorite meal is mushroom stew with dumplings.',
    'She loves lifting heavy things for grateful neighbors.',
    'Bastion remembers every promise she makes.',
    'She braids her hair when solving hard problems.',
    'Her room contains more blankets than furniture.',
    'She carves little wooden animals during long watches.',
    'Bastion always volunteers to carry the picnic basket.',
    'She is gentle with spiders and relocates them outside.',
    'Her favorite flower is the sturdy little snowdrop.',
    'She laughs hardest at very bad puns.',
    'Bastion can repair almost any broken chair.',
    'She drinks warm milk with nutmeg before bed.',
    'Her hugs are famous throughout the company.',
    'She enjoys competitive arm wrestling a little too much.',
    'Bastion keeps emergency cookies in a shield compartment.',
    'She likes dogs that believe they are lap-sized.',
    'Her handwriting is broad, round, and cheerful.',
    'She sings old marching songs while doing laundry.',
    'Bastion collects smooth stones from meaningful places.',
    'She plans surprise parties with military precision.',
    'Her favorite weather is a soft, steady snowfall.',
    'She never starts dinner until everyone is seated.',
    'Bastion makes excellent hot cider.',
    'She loves historical dramas with elaborate costumes.',
    'Her guilty pleasure is glittery stationery.',
    'She checks every lock twice, then trusts it.',
    'Bastion teaches children how to build blanket forts.',
    'She keeps her oldest scarf despite countless repairs.',
    'Her ideal morning begins with stretching and toast.',
    'She apologizes to tables after bumping into them.',
    'Bastion knows the birthday of every squadmate.',
    'She gives practical gifts wrapped beautifully.',
    'Her favorite fruit is a perfectly crisp apple.',
    'She loves watching blacksmiths work.',
    'Bastion is terrible at whispering secrets.',
    'She keeps pressed leaves in her training journal.',
    'Her tea preference is strong, sweet, and enormous.',
    'She always offers the last chair to someone else.',
    'Bastion’s dream home has a huge communal table.',
    'She can knit one very specific kind of sock.',
    'Her favorite music has drums she can march to.',
    'She cries at reunions in adventure stories.',
    'Bastion makes friends with every innkeeper.',
    'She prefers sunrise hikes with plenty of snacks.',
    'Her armor polish smells faintly of oranges.',
    'She keeps a list of people who need checking on.',
    'Bastion treasures handmade gifts above everything.',
    'Her perfect evening is feeding a crowded table.',
  ],
  warden: [
    'Warden knows exactly how everyone takes their tea.',
    'She keeps fresh flowers beside every sickbed.',
    'Her favorite food is soft rice with ginger.',
    'She mends torn sleeves before anyone notices.',
    'Warden collects lullabies from every town she visits.',
    'She can make a room feel quieter by entering it.',
    'Her windowsill is crowded with medicinal herbs.',
    'She loves gentle watercolor landscapes.',
    'Warden never forgets to bring an umbrella.',
    'She writes letters for people who cannot find words.',
    'Her favorite animal is the luna moth.',
    'She keeps peppermint candies for nervous friends.',
    'Warden enjoys slow walks through botanical gardens.',
    'She has a surprisingly mischievous poker face.',
    'Her comfort book has been repaired seven times.',
    'She prefers lavender soap and clean linen.',
    'Warden makes tiny soups when someone feels ill.',
    'She hums while organizing medicine bottles.',
    'Her favorite season is tender early spring.',
    'She loves hearing people talk about their hometowns.',
    'Warden owns one pair of outrageously bright socks.',
    'She leaves encouraging notes inside borrowed books.',
    'Her ideal breakfast is peaches and warm oats.',
    'She can recognize friends by their footsteps.',
    'Warden is unbeatable at memory games.',
    'She saves ribbon from every meaningful gift.',
    'Her garden has a bench reserved for visitors.',
    'She prefers candlelight to harsh lamps.',
    'Warden knows when silence is the kinder answer.',
    'She bakes delicate almond biscuits on rainy days.',
    'Her laugh starts quietly and becomes contagious.',
    'She loves tiny birds with enormous confidence.',
    'Warden carries a comb for windswept companions.',
    'She makes birthdays feel like holidays.',
    'Her favorite color is lilac at dusk.',
    'She keeps a gratitude list in coded shorthand.',
    'Warden naps best beside a crackling fireplace.',
    'She can fold fitted sheets perfectly.',
    'Her dream trip follows old lighthouse roads.',
    'She enjoys guessing the ingredients in unfamiliar tea.',
    'Warden gives every plant a dignified name.',
    'She remembers stories better than dates.',
    'Her favorite dessert is vanilla custard with berries.',
    'She loves quietly watching markets open at dawn.',
    'Warden always carries an extra pair of gloves.',
    'She is deeply competitive about crossword puzzles.',
    'Her room smells like cedar and chamomile.',
    'She treasures candid photographs of her friends.',
    'Warden believes a warm meal solves many problems.',
    'Her perfect night ends with everyone safely home.',
  ],
  nyx: [
    'Nyx befriends alley cats by pretending not to.',
    'She orders noodles at the maximum spice level.',
    'Her favorite hour is exactly two in the morning.',
    'She collects earrings that do not quite match.',
    'Nyx reads ghost stories under three blankets.',
    'She knows every rooftop shortcut in the city.',
    'Her laugh appears when she is trying to look serious.',
    'She loves blackberries straight from the vine.',
    'Nyx can sleep through thunder but not dripping taps.',
    'She keeps movie-ticket stubs in her wallet.',
    'Her favorite color is blue just before sunrise.',
    'She is excellent at claw-machine games.',
    'Nyx wears perfume that smells faintly of rain.',
    'She loves tiny cafés with questionable lighting.',
    'Her comfort food is crispy scallion pancakes.',
    'She sketches strangers’ shoes while waiting.',
    'Nyx sends friends songs instead of long messages.',
    'She collects strange keys with unknown locks.',
    'Her ideal pet is an elderly one-eyed cat.',
    'She prefers silver nail polish chipped at the edges.',
    'Nyx knows several card tricks and one real trick.',
    'She steals blankets and denies everything.',
    'Her favorite flowers bloom only at night.',
    'She enjoys train rides to nowhere in particular.',
    'Nyx writes poetry and hides it extremely well.',
    'She can pick the ripest peach by scent.',
    'Her room is messy in a highly navigable way.',
    'She loves old buildings with secret staircases.',
    'Nyx always chooses the most dramatic umbrella.',
    'She makes exceptional midnight grilled cheese.',
    'Her playlists have titles nobody else understands.',
    'She prefers moonlit swims to sunny beaches.',
    'Nyx secretly enjoys cheerful romantic comedies.',
    'She keeps a coin from her first solo journey.',
    'Her favorite game is hide-and-seek, naturally.',
    'She loves the sound of a distant train.',
    'Nyx remembers every cat’s preferred scratching spot.',
    'She uses fancy bookmarks in cheap paperbacks.',
    'Her dream apartment has an impossible number of windows.',
    'She is always first to spot a shooting star.',
    'Nyx gives excellent gifts with no explanation.',
    'She likes smoky tea and sweet buns.',
    'Her handwriting changes with her mood.',
    'She has never returned a borrowed hoodie.',
    'Nyx relaxes by solving elaborate escape rooms.',
    'She keeps polished stones lined along the sill.',
    'Her favorite dessert is dark cherry ice cream.',
    'She enjoys museums after closing hours, somehow.',
    'Nyx always notices the nearest exit and bakery.',
    'Her best mornings begin very late.',
  ],
  tempest: [
    'Tempest opens windows whenever a storm arrives.',
    'She drums rhythms on every available tabletop.',
    'Her favorite snack is salted watermelon.',
    'She builds tiny radios from discarded parts.',
    'Tempest loves swimming when the water is cold.',
    'She can predict rain by the smell of stone.',
    'Her hair refuses to obey any brush.',
    'She collects glass marbles that resemble planets.',
    'Tempest dances while waiting for kettles to boil.',
    'She prefers fizzy drinks with too much lime.',
    'Her favorite color is electric blue.',
    'She once repaired a fan just to improve it.',
    'Tempest talks faster when she is excited.',
    'She loves concerts where the floor vibrates.',
    'Her ideal breakfast includes three kinds of fruit.',
    'She races elevators up the stairs.',
    'Tempest keeps spare batteries in labeled tins.',
    'She can whistle louder than anyone expects.',
    'Her favorite animal is the hummingbird.',
    'She enjoys photographing unusual cloud shapes.',
    'Tempest makes friendship bracelets with metallic thread.',
    'She loves roller skates and open plazas.',
    'Her room contains several harmless unfinished inventions.',
    'She orders dessert before choosing dinner.',
    'Tempest knows every good swimming hole nearby.',
    'She sleeps with a fan running all year.',
    'Her favorite candy crackles on the tongue.',
    'She keeps concert wristbands around her bedpost.',
    'Tempest is very bad at sitting through lectures.',
    'She makes excellent playlists for road trips.',
    'Her dream home has a rooftop weather station.',
    'She loves bright sneakers and reflective laces.',
    'Tempest names storms after inconvenient acquaintances.',
    'She can juggle three oranges for almost a minute.',
    'Her favorite dessert is lemon sorbet.',
    'She gives enthusiastic, slightly dangerous high-fives.',
    'Tempest fixes lamps before anyone asks.',
    'She likes science museums with working buttons.',
    'Her handwriting leans forward like it is running.',
    'She treasures voice messages full of laughter.',
    'Tempest prefers windy cliffs to quiet valleys.',
    'She grows mint because it survives her schedule.',
    'Her favorite films contain impossible airships.',
    'She turns chores into timed competitions.',
    'Tempest always carries a tiny screwdriver.',
    'She likes thunderstorms best when friends are nearby.',
    'Her perfect evening includes music and street food.',
    'She can make sparks dance between her fingertips.',
    'Tempest celebrates good news with cartwheels.',
    'She never refuses an invitation to karaoke.',
  ],
  briar: [
    'Briar grows roses in chipped teacups.',
    'She makes strawberry jam every early summer.',
    'Her favorite dress has enormous pockets.',
    'She talks to seedlings while watering them.',
    'Briar loves outdoor dances under string lights.',
    'She braids wildflowers into everyone’s hair.',
    'Her comfort meal is tomato soup and toast.',
    'She keeps bees and knows each hive’s temperament.',
    'Briar collects floral china with tiny cracks.',
    'She laughs whenever mud ruins her shoes.',
    'Her favorite color is the inside of a rose.',
    'She can identify herbs with her eyes closed.',
    'Briar makes excellent berry pies.',
    'She prefers handwritten invitations to formal events.',
    'Her room always contains one mysterious vine.',
    'She loves farmers’ markets before they get crowded.',
    'Briar presses leaves into homemade paper.',
    'She dances barefoot whenever possible.',
    'Her favorite animal is the sleepy bumblebee.',
    'She keeps ribbon tied around garden tools.',
    'Briar sends cuttings instead of greeting cards.',
    'She knows which flowers open after rain.',
    'Her ideal picnic includes cheese and plums.',
    'She enjoys painting little signs for herb pots.',
    'Briar is fiercely competitive at croquet.',
    'She wears perfume made from her own garden.',
    'Her favorite season is late, overgrown summer.',
    'She gives every scarecrow a proper backstory.',
    'Briar can weave a flower crown in minutes.',
    'She loves old songs with easy harmonies.',
    'Her dream cottage has a glass greenhouse.',
    'She keeps a secret stash of sour candies.',
    'Briar makes bouquets for people having hard weeks.',
    'She prefers freckles to perfect makeup.',
    'Her handwriting curls like climbing ivy.',
    'She knows how to remove almost any stain.',
    'Briar loves warm rain and garden mud.',
    'She collects recipes written in family margins.',
    'Her favorite dessert is rosewater shortbread.',
    'She can whistle birds into curious silence.',
    'Briar hosts dinners with mismatched plates.',
    'She dries orange slices for winter garlands.',
    'Her favorite jewelry is made from pressed petals.',
    'She believes every windowsill deserves something green.',
    'Briar relaxes by pruning plants at sunset.',
    'She never wastes the last spoonful of honey.',
    'Her perfect morning begins barefoot in the garden.',
    'She gives plants to friends moving somewhere new.',
    'Briar always smells faintly of crushed mint.',
    'She saves the first blossom of every spring.',
  ],
  seraph: [
    'Seraph watches sunrise even after very late nights.',
    'She knows the best pastry in every town.',
    'Her favorite fruit is a chilled golden peach.',
    'She collects feathers without taking them from birds.',
    'Seraph paints tiny suns on ordinary objects.',
    'She loves rooftop breakfasts with strong coffee.',
    'Her laugh makes other people start laughing.',
    'She keeps bright ribbons tied to her luggage.',
    'Seraph volunteers to take every group photograph.',
    'She can make pancakes shaped like animals.',
    'Her favorite color is apricot at dawn.',
    'She sings harmony without needing to practice.',
    'Seraph owns too many pairs of sunglasses.',
    'She sends postcards from places she barely visited.',
    'Her ideal meal is warm bread and citrus salad.',
    'She loves public gardens full of fountains.',
    'Seraph remembers compliments for years.',
    'She keeps a sketchbook of interesting doorways.',
    'Her favorite animal is the sun conure.',
    'She wears gold nail polish on difficult days.',
    'Seraph believes every room needs better lighting.',
    'She makes excellent orange marmalade.',
    'Her dream trip follows the coast by train.',
    'She enjoys teaching children simple songs.',
    'Seraph always finds the warmest patch of sunlight.',
    'She carries spare hair ties for everyone.',
    'Her favorite dessert is cardamom cream cake.',
    'She loves old theaters with painted ceilings.',
    'Seraph celebrates tiny victories with sparkling drinks.',
    'She can nap peacefully on sunny stone steps.',
    'Her handwriting is large, elegant, and optimistic.',
    'She gives plants more sunlight than instructions recommend.',
    'Seraph likes dresses that move when she spins.',
    'She keeps breakfast invitations delightfully informal.',
    'Her favorite season is the bright edge of spring.',
    'She enjoys portraits that catch people laughing.',
    'Seraph can braid ribbon into almost anything.',
    'She orders the most colorful thing on the menu.',
    'Her room smells like orange blossom and paper.',
    'She loves flying kites from windy hills.',
    'Seraph keeps every child’s drawing she receives.',
    'She is surprisingly skilled at table tennis.',
    'Her perfect afternoon includes a sunny bookshop.',
    'She makes playlists for the first day of trips.',
    'Seraph always opens curtains before making tea.',
    'She likes earrings that catch the light.',
    'Her comfort food is buttered noodles with herbs.',
    'She knows exactly when peaches become ripe.',
    'Seraph ends letters with a tiny drawn sun.',
    'Her best ideas arrive during long morning walks.',
  ],
  rapunsel: [
    'I braid my hair differently whenever I need a fresh start.',
    'I am an adult, but I still order the dessert with the tiny paper umbrella.',
    'I keep ribbon in every coat pocket just in case.',
    'I love strawberry milk and cinnamon toast.',
    'I can sit on my hair if I forget where I left the end of it.',
    'I apologize to furniture when my braid knocks something over.',
    'I collect illustrated fairy tales with ridiculous endings.',
    'I like soft sweaters with sleeves that cover my hands.',
    'I have learned forty-seven different kinds of braid.',
    'I spend quiet afternoons sketching people in cafés.',
    'I always carry extra hair ties for everyone else.',
    'I prefer window seats, especially when it is raining.',
    'I bake tiny cakes because large cakes feel too serious.',
    'I love yellow flowers growing in unexpected places.',
    'I talk to my hair when it refuses to cooperate.',
    'I have a favorite comb carved from pear wood.',
    'I wear simple dresses so my braid can be the dramatic part.',
    'I can fall asleep almost anywhere if there is a warm blanket.',
    'I keep pressed daisies inside my recipe book.',
    'I enjoy picnics even when the wind ruins everything.',
    'I sing quietly while untangling knots.',
    'I love small dogs with enormous confidence.',
    'I make excellent honey biscuits.',
    'I prefer gentle colors and very strong tea.',
    'I laugh whenever someone underestimates how heavy my hair is.',
    'I have never found a hat that truly works.',
    'I keep my room neat except for one impossible chair of clothes.',
    'I like museums with costume exhibits.',
    'I can weave a flower crown without looking down.',
    'I save pretty wrapping paper for future projects.',
    'I own a tiny silver mirror that belonged to my grandmother.',
    'I love the first warm afternoon after winter.',
    'I send voice messages because my hands are usually busy braiding.',
    'I make playlists with names that sound like story chapters.',
    'I am shy at large parties and fearless at small dinners.',
    'I order peach tea whenever it is on the menu.',
    'I enjoy sewing pockets into dresses that should have had them already.',
    'I know how to turn a bad hair day into a defensive weapon.',
    'I keep a notebook of places I want to visit by train.',
    'I love earrings shaped like little moons.',
    'I can remember a compliment for years.',
    'I would rather receive a handwritten note than an expensive gift.',
    'I wear my longest braid when I need courage.',
    'I like watching storms from a safely covered balcony.',
    'I always save the softest pillow for a guest.',
    'I have a weakness for miniature pastries.',
    'I relax by brushing my hair exactly one hundred strokes.',
    'I believe kindness should feel practical, not performative.',
    'I dream of a bright apartment with very high ceilings.',
    'I end difficult days by braiding one small flower into my hair.',
  ],
}

const CHARACTER_NAMES: Record<CharacterId, string> = {
  vesper: 'Vesper', cinder: 'Scarlet', bastion: 'Bastion', warden: 'Warden', nyx: 'Nyx',
  tempest: 'Tempest', briar: 'Briar', seraph: 'Seraph', rapunsel: 'Rapunsel',
}

const FIRST_PERSON_ADVERBS = new Set(['always', 'never', 'secretly', 'deeply', 'quietly', 'usually', 'really', 'once', 'also', 'just'])
const firstPersonVerb = (word: string): string => {
  const punctuation = word.match(/[.,;:!?]+$/)?.[0] ?? ''
  const bare = word.slice(0, word.length - punctuation.length)
  const lower = bare.toLowerCase()
  const irregular: Record<string, string> = { is: 'am', has: 'have', does: 'do', goes: 'go' }
  let next = irregular[lower] ?? bare
  if (!irregular[lower] && !['can', 'could', 'would', 'should', 'will', 'may', 'might', 'must'].includes(lower)) {
    if (/ies$/i.test(bare)) next = `${bare.slice(0, -3)}y`
    else if (/(ches|shes|xes|zes|oes|sses)$/i.test(bare)) next = bare.slice(0, -2)
    else if (/s$/i.test(bare) && !/ss$/i.test(bare)) next = bare.slice(0, -1)
  }
  return `${next}${punctuation}`
}

const replaceInternalPronouns = (text: string): string => text
  .replace(/\b[Ss]he\s+([A-Za-z-]+)/g, (_match, verb: string) => `I ${firstPersonVerb(verb)}`)
  .replace(/\b[Hh]erself\b/g, 'myself')
  .replace(/\b[Hh]er\b/g, 'my')

const toFirstPerson = (character: CharacterId, fact: string): string => {
  if (/^I(?:\b|['’])/.test(fact)) return fact
  const name = CHARACTER_NAMES[character]
  const subject = new RegExp(`^(?:${name}|She)\\s+`)
  if (subject.test(fact)) {
    const words = replaceInternalPronouns(fact.replace(subject, '')).split(' ')
    let verbIndex = 0
    while (verbIndex < words.length - 1 && FIRST_PERSON_ADVERBS.has(words[verbIndex].toLowerCase().replace(/[^a-z]/g, ''))) verbIndex += 1
    words[verbIndex] = firstPersonVerb(words[verbIndex])
    return `I ${words.join(' ')}`
  }
  const possessive = fact
    .replace(new RegExp(`^${name}[’']s\\s+`), 'my ')
    .replace(/^Her\s+/, 'my ')
  const converted = replaceInternalPronouns(possessive)
  return `I'll admit, ${converted.charAt(0).toLowerCase()}${converted.slice(1)}`
}

export const PERSONALITY_FACTS: Record<CharacterId, readonly string[]> = Object.fromEntries(
  (Object.keys(RAW_PERSONALITY_FACTS) as CharacterId[]).map((character) => [
    character,
    RAW_PERSONALITY_FACTS[character].map((fact) => toFirstPerson(character, fact)),
  ]),
) as unknown as Record<CharacterId, readonly string[]>

export const personalityFact = (character: CharacterId, seed: number): string => {
  const facts = PERSONALITY_FACTS[character]
  return facts[Math.abs(seed) % facts.length]
}
